TestASP/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TestASP.DataAccess.Repository.IRepository;
using TestASP.Models;
using TestASP.Models.ViewModels;
using TestASP.Utility;

namespace TestASP.Controllers
{
    [Authorize(Roles = SD.Role_HR)]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Employee> Employee_List = _unitOfWork.EmployeeRepository.GetAll(includeProperties: "Department").ToList();
            return View(Employee_List);
        }

        public IActionResult Insert()
        {
            EmployeeVM add = new EmployeeVM();
            add.Department_List = _unitOfWork.DepartmentRepository.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(add);
        }

        [HttpPost]
        public IActionResult Insert(EmployeeVM add)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.EmployeeRepository.Add(add.Employee);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            add.Department_List = _unitOfWork.DepartmentRepository.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(add);
        }

        public IActionResult Update(Guid Id)
        {
            EmployeeVM edit = new EmployeeVM();
            edit.Employee = _unitOfWork.EmployeeRepository.Get(u => u.Id == Id);
            if(edit.Employee == null)
            {
                return NotFound();
            }
            edit.Department_List = _unitOfWork.DepartmentRepository.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(edit);
        }

        [HttpPost]
        public IActionResult Update(EmployeeVM edit)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.EmployeeRepository.Update(edit.Employee);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            edit.Department_List = _unitOfWork.DepartmentRepository.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(edit);
        }

        [HttpGet]
        public IActionResult Delete(Guid Id)
        {
            Employee employee = _unitOfWork.EmployeeRepository.Get(U => U.Id == Id);
            if (employee == null)
            {
                return NotFound();
            }
            _unitOfWork.EmployeeRepository.Remove(employee);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

TestASP/Controllers/LeaveController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using TestASP.DataAccess.Repository.IRepository;
using TestASP.Models;
using TestASP.Models.ViewModels;
using TestASP.Utility;

namespace TestASP.Controllers
{
    [Authorize]
    public class LeaveController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        public LeaveController(
            IUnitOfWork unitOfWork,
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            if (User.IsInRole(SD.Role_HR))
            {
                return RedirectToAction("GetAllLeave");
            }
            else
            {
                return RedirectToAction("GetMyLeave");
            }
        }

        [Authorize(Roles = SD.Role_HR)]
        public IActionResult GetAllLeave(GetAllLeaveVM? vm)
        {
            vm.LeaveList = _unitOfWork.LeaveRecordRepository.Filter(vm.EmployeeCode, vm.DepartmentName, vm.From, vm.To);

            foreach (var leave in vm.LeaveList)
            {
                leave.Employee = _unitOfWork.EmployeeRepository.Get(u => u.Id == leave.EmployeeId);
            }

            foreach (var leave in vm.LeaveList)
            {
                leave.Employee.Department = _unitOfWork.DepartmentRepository.Get(u => u.Id == leave.Employee.DepartmentId);
            }
            foreach (var leave in vm.LeaveList)
            {
                leave.LeaveType = _unitOfWork.LeaveTypeRepository.Get(u => u.Id == leave.LeaveTypeId);
            }
            return View(vm);
        }

        public IActionResult GetMyLeave()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
            string userId = claim.Value;

            Employee employee = _unitOfWork.EmployeeRepository.Get(u => u.UserId == userId);

            List<LeaveRecord> leaveList = _unitOfWork.LeaveRecordRepository.GetAll(u => u.EmployeeId == employee.Id, includeProperties: "LeaveType").ToList();
            return View(leaveList);
        }

        public IActionResult AddLeave()
        {
            LeaveVM add = new LeaveVM();
            add.Leave_Type_List = _unitOfWork.LeaveTypeRepository.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(add);
        }

        [HttpPost]
        public IActionResult AddLeave(LeaveVM add)
        {
            if (ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
                string userId = claim.Value;

                Employee employee = _unitOfWork.EmployeeRepository.Get(u => u.UserId == userId);
                add.LeaveRecord.EmployeeId = employee.Id;
                _unitOfWork.LeaveRecordRepository.Add(add.LeaveRecord);
                _unitOfWork.Save();
                return RedirectToAction("GetMyLeave");
            }
            add.Leave_Type_List = _unitOfWork.LeaveTypeRepository.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(add);
        }
    }
}

TestASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestASP.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/responsive/2.4.0/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if (User.IsInRole(SD.Role_HR))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">รายชื่อพนักงาน</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leave" asp-action="GetMyLeave">การลาของฉัน</a>
                        </li>
                        @{
                            if (User.IsInRole(SD.Role_HR))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Leave" asp-action="GetAllLeave">ข้อมูลการลาทั้งหมด</a>
                                </li>
                            }
                        }
                        
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/plug-ins/1.13.7/api/sum().js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>